name: web-php-fpm
services:
  docker-nginx-php-fpm:
    container_name: web-php-fpm
    ports:
      - 10001:80
    volumes:
      - ./config/nginx_default.conf:/etc/nginx/conf.d/default.conf
      - ./website:/var/www/html:ro
    image: ghcr.io/breadhub-org/docker-nginx-php-fpm:8.0