name: Docker
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - LICENSE
      - README.md
  schedule:
  - cron: '0 0 */7 * *'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
    - name: Build 7.3
      uses: docker/build-push-action@v2
      with:
        push: true
        file: 7.3/Dockerfile
        platforms: linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:7.3

    - name: Build 7.3 Buster
      uses: docker/build-push-action@v2
      with:
        push: true
        file: 7.3-apache/Dockerfile
        platforms: linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:7.3-buster

    - name: Build 7.4
      uses: docker/build-push-action@v2
      with:
        push: true
        file: 7.4/Dockerfile
        platforms: linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:7.4,${{ env.REGISTRY }}/${{ github.repository }}:7

    - name: Build 7.4 Buster
      uses: docker/build-push-action@v2
      with:
        push: true
        file: 7.4-debian/Dockerfile
        platforms: linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:7.4-buster,${{ env.REGISTRY }}/${{ github.repository }}:7-buster

    - name: Build 8.0
      uses: docker/build-push-action@v2
      with:
        push: true
        file: 8.0/Dockerfile
        platforms: linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:8,${{ env.REGISTRY }}/${{ github.repository }}:8.0,${{ env.REGISTRY }}/${{ github.repository }}:latest

    - name: Build 8.0 Buster
      uses: docker/build-push-action@v2
      with:
        push: true
        file: 8.0-debian/Dockerfile
        platforms: linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:8-buster,${{ env.REGISTRY }}/${{ github.repository }}:8.0-buster,${{ env.REGISTRY }}/${{ github.repository }}:latest-buster