name: CI
on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build 7.3
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: |
          PHP_VERSION=7.3
          ALPINE_VERSION=3.13
        tags: olkitu/docker-nginx-php-fpm:7.3

    - name: Build 7.4
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: |
          PHP_VERSION=7.4
          ALPINE_VERSION=3.13
        tags: olkitu/docker-nginx-php-fpm:latest,olkitu/docker-nginx-php-fpm:7.4

    - name: Build Latest
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: |
          PHP_VERSION=8
          ALPINE_VERSION=3.13
        tags: olkitu/docker-nginx-php-fpm:latest,olkitu/docker-nginx-php-fpm:8

    - name: Update repo description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: olkitu/docker-nginx-php-fpm